# Generated by Django 6.1.1 on 2026-10-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_id', models.CharField(max_length=32, unique=True)),
                ('interaction_type', models.PositiveSmallIntegerField()),
                ('command_name', models.CharField(blank=True, max_length=64)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('guild_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('channel_id', models.CharField(blank=True, max_length=32)),
                ('user_id', models.CharField(blank=True, max_length=32)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=16)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
