# Generated by Django 6.1.1 on 2026-10-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandlog',
            name='action',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='commandlog',
            name='mirror_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commandlog',
            name='mirror_last_error',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='commandlog',
            name='mirror_status',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='not_applicable', max_length=16),
        ),
    ]
