# Generated by Django 6.1.1 on 2026-10-01 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bot', '0002_commandlog_action_commandlog_mirror_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MirrorAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.PositiveSmallIntegerField()),
                ('ok', models.BooleanField()),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='discord_bot.commandlog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
