# Generated by Django 6.1.1 on 2026-10-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bot', '0003_mirrorattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('command_name', models.CharField(default='report', max_length=64)),
                ('keywords', models.TextField(help_text='Comma-separated. Matches if any keyword appears.')),
                ('action', models.CharField(default='flagged_urgent', max_length=32)),
                ('mirror', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=10, help_text='Lower runs first')),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
    ]
